set nocompatible

filetype plugin on
filetype indent on
syntax on

set noswapfile nobackup

" remove default ~/.vim directories to avoid loading plugins
set runtimepath-=~/.vim
set runtimepath-=~/.vim/after

function! VimrunnerEvaluateCommandOutput(command)
  let base_command = split(a:command, '\s\+')[0]
  let base_command = substitute(base_command, '!$', '', '')

  if !exists(':'.base_command)
    let output = 'Vim:E492: Not an editor command: '.base_command
  else
    redir => output
    silent exe a:command
    redir END
  endif

  return output
endfunction
