set nocompatible

filetype plugin on
filetype indent on
syntax on

set noswapfile nobackup

" remove default ~/.vim directories to avoid loading plugins
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
