set nocompatible

filetype plugin on
filetype indent on
syntax on

set noswapfile nobackup

" remove default ~/.vim directories to avoid loading plugins
set runtimepath-=~/.vim
set runtimepath-=~/.config/vim
set runtimepath-=~/.vim/after
set runtimepath-=~/.config/vim/after
